// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workplace.Web.Data;

#nullable disable

namespace Workplace.Web.Migrations
{
    [DbContext(typeof(WorkplaceDbContext))]
    [Migration("20260903074603_AddCalendarDisplayName")]
    partial class AddCalendarDisplayName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Workplace.Web.Data.CalendarColorSetting", b =>
                {
                    b.Property<string>("CalendarKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("CalendarKey");

                    b.ToTable("CalendarColorSettings");
                });

            modelBuilder.Entity("Workplace.Web.Data.ConnectedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRefreshError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRefreshedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("ConnectedAccounts");
                });

            modelBuilder.Entity("Workplace.Web.Data.WorkCalendarSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkCalendarSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
